spring:
  #redis配置
  redis:
    database: 2
    host: 47.106.199.193
    port: 1371
    password: '*&(*%QWaf4534!123dsg'
    timeout: 20000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  #数据库配置
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: 123456
          url: jdbc:mysql://192.168.1.79:3306/citymanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 6000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              #login-username: admin
              #login-password: admin
            filter:
              stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: false
              wall:
                config:
                  multi-statement-allow: true
#        orcale:
#          username: query
#          password: 888888
#          url: jdbc:oracle:thin:@192.168.3.35:1521/xhdb
#          driver-class-name: oracle.jdbc.OracleDriver
#          druid: # 以下参数针对每个库可以重新设置druid参数
#            initial-size: 10
#            max-active: 100
#            min-idle: 10
#            max-wait: 6000
#            pool-prepared-statements: true
#            max-pool-prepared-statement-per-connection-size: 20
#            time-between-eviction-runs-millis: 60000
#            min-evictable-idle-time-millis: 300000
#            #Oracle需要打开注释
#            #validation-query: SELECT 1 FROM DUAL
#            test-while-idle: true
#            test-on-borrow: false
#            test-on-return: false
#            stat-view-servlet:
#              enabled: true
#              url-pattern: /druid/*
#              #login-username: admin
#              #login-password: admin
#            filter:
#              stat:
#                log-slow-sql: true
#                slow-sql-millis: 1000
#                merge-sql: false
#              wall:
#                config:
#                  multi-statement-allow: true


    #kafka
  kafka:
    consumer:
      bootstrap-servers: 10.253.36.37:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest                       #最早未被消费的offset earliest
      max-poll-records: 200                         #批量消费一次最大拉取的数据量
      enable-auto-commit: false                         #是否开启自动提交
      auto-commit-interval: 1000                        #自动提交的间隔时间
    listener:
      ack-mode: MANUAL_IMMEDIATE
      type: BATCH                                #是否开启批量消费，true表示批量消费
      concurrency: 1                                  #设置消费的线程数
      poll-timeout: 1500

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

check:
  sql: # 考评sql配置
    url: http://192.168.1.72:9090
    sqlType: MYSQL-DB-server,PostgreSQL
    apikey: 154e1ff58e5e66db2a8e524b41eff082
    middlewareType: Tomcat-server
  server:
    url: http://192.168.1.75:8060
    name: Server
    apikey: 641f6dae7d050b04898187bbdb35bc4f
  order:
    url: http://192.168.1.73:8080
    apikey: 0125E6D6-8D59-4E23-9104-ACE745F6BF37
client:
  url: https://iam.szzhcg.com
  client-id: apphub_oauth
  client-secret: 0427f05a070d45169da2ad5aed47b8ed







